name: Build and Deploy
on: 
  push:
    branches: [master]

jobs: 
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy python bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd /var/www/pb_throw_snowball
            git pull
            docker build -t pb_throw_snowball . # остается рестартануть контейнер со всеми env переменными
            docker run -d --env-file .env --name pb_throw_snowball --network network_local pb_throw_snowball
            
            
